<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.0.1</Version>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>x64</Platforms>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <BuildForWindows>True</BuildForWindows>
    <BuildForWindowsStore>True</BuildForWindowsStore>
    <ModuleId>$(MSBuildProjectName)</ModuleId>
    <ModuleName>$(MSBuildProjectName)</ModuleName>
    <ModuleUrl></ModuleUrl>
    <GameFolder>$(BANNERLORD_GAME_DIR)</GameFolder>
    <GameBinariesFolder Condition="Exists('$(GameFolder)\bin\Win64_Shipping_Client')">Win64_Shipping_Client</GameBinariesFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bannerlord.MCM" Version="5.11.4" />
    <PackageReference Include="Bannerlord.ReferenceAssemblies" Version="1.4.5.115026" />
    <PackageReference Include="Bannerlord.UIExtenderEx" Version="2.13.2" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /Y &quot;C:\Users\kille\Desktop\Modding\Bannerlord\Bannerlord Repos\PartyAIControls\src\PartyAIControls\bin\x64\Debug\netstandard2.0\PartyAIControls.dll&quot; &quot;C:\Program Files\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\PartyAIControls\bin\Win64_Shipping_Client\PartyAIControls.dll&quot;" />
	</Target>

</Project>